### ISSUE TITLE
Internal Scripts missing

### ISSUE THREAD

**Issue by tokejepsen** [Colorbleed/colorbleed-config#142]
**Problem**

```
# Error: ImportError: file C:\Users\admin\colorbleed-config\colorbleed\maya\menu.py line 26: No module named scriptsmenu.launchformaya # 
```

Seems like there are internal scripts in this config.

**Comment by BigRoy** [comment]
Thanks for reporting! 

I am on holiday until 18th of August, afterwards I will have another look. Would be good if we can ensure all dependencies work. :)

**Comment by aardschok** [comment]
This is a dependency issue which we should mention in the `README`.
The `scriptsmenu` can be found [here](https://github.com/Colorbleed/scriptsmenu), add its directory to your PYTHONPATH. 

It is a bit nicer to do that dependency check prior to trying to install the menu.
